
import java.sql.Connection;
import java.sql.DriverManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dalbir Singh
 */
public class EducationalDetailsUni extends javax.swing.JFrame {

    /**
     * Creates new form EducationalDetailsUni
     */
    public EducationalDetailsUni() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        generalToggle = new javax.swing.JButton();
        proectToggle = new javax.swing.JButton();
        experienceToggle = new javax.swing.JButton();
        confirmationToggle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userUniversityDegreeName = new javax.swing.JTextField();
        userUniversityBranch = new javax.swing.JTextField();
        userUniversityCollegeName = new javax.swing.JTextField();
        userUniversityBatchYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userUniversitySem1 = new javax.swing.JTextField();
        userUniversitySem2 = new javax.swing.JTextField();
        userUniversitySem3 = new javax.swing.JTextField();
        userUniversitySem4 = new javax.swing.JTextField();
        userUniversitySem5 = new javax.swing.JTextField();
        userUniversitySem6 = new javax.swing.JTextField();
        userUniversitySem7 = new javax.swing.JTextField();
        userUniversitySem8 = new javax.swing.JTextField();
        saveEduUniversityInfo = new javax.swing.JButton();
        EduHscSscToggle = new javax.swing.JButton();
        userId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 4));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("                  EDUCATIONAL DETAILS OF UNIVERSITY");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 4));

        generalToggle.setBackground(new java.awt.Color(51, 51, 51));
        generalToggle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        generalToggle.setForeground(new java.awt.Color(204, 204, 204));
        generalToggle.setText("GENERAL");
        generalToggle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        generalToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalToggleActionPerformed(evt);
            }
        });

        proectToggle.setBackground(new java.awt.Color(51, 51, 51));
        proectToggle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        proectToggle.setForeground(new java.awt.Color(204, 204, 204));
        proectToggle.setText("PROJECTS / INTERNSHIPS");
        proectToggle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        proectToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proectToggleActionPerformed(evt);
            }
        });

        experienceToggle.setBackground(new java.awt.Color(51, 51, 51));
        experienceToggle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        experienceToggle.setForeground(new java.awt.Color(204, 204, 204));
        experienceToggle.setText("EXPERIENCE");
        experienceToggle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        experienceToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experienceToggleActionPerformed(evt);
            }
        });

        confirmationToggle.setBackground(new java.awt.Color(51, 51, 51));
        confirmationToggle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        confirmationToggle.setForeground(new java.awt.Color(204, 204, 204));
        confirmationToggle.setText("CONFIRMATION");
        confirmationToggle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        confirmationToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationToggleActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("DEGREE NAME");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("BRANCH");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("BATCH YEAR");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("COLLEGE NAME");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        userUniversityDegreeName.setBackground(new java.awt.Color(204, 204, 204));
        userUniversityDegreeName.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        userUniversityDegreeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversityBranch.setBackground(new java.awt.Color(204, 204, 204));
        userUniversityBranch.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        userUniversityBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversityCollegeName.setBackground(new java.awt.Color(204, 204, 204));
        userUniversityCollegeName.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        userUniversityCollegeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversityBatchYear.setBackground(new java.awt.Color(204, 204, 204));
        userUniversityBatchYear.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        userUniversityBatchYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("SEM 1");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("SEM 2");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CGPA OF SEMESTERS");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("SEM 3");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("SEM 8");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("SEM 6");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("SEM 7");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("SEM 5");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("SEM 4");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        userUniversitySem1.setBackground(new java.awt.Color(204, 204, 204));
        userUniversitySem1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        userUniversitySem1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUniversitySem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        userUniversitySem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userUniversitySem1ActionPerformed(evt);
            }
        });

        userUniversitySem2.setBackground(new java.awt.Color(204, 204, 204));
        userUniversitySem2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        userUniversitySem2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUniversitySem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversitySem3.setBackground(new java.awt.Color(204, 204, 204));
        userUniversitySem3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        userUniversitySem3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUniversitySem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversitySem4.setBackground(new java.awt.Color(204, 204, 204));
        userUniversitySem4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        userUniversitySem4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUniversitySem4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversitySem5.setBackground(new java.awt.Color(204, 204, 204));
        userUniversitySem5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        userUniversitySem5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUniversitySem5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversitySem6.setBackground(new java.awt.Color(204, 204, 204));
        userUniversitySem6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        userUniversitySem6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUniversitySem6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversitySem7.setBackground(new java.awt.Color(204, 204, 204));
        userUniversitySem7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        userUniversitySem7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUniversitySem7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        userUniversitySem8.setBackground(new java.awt.Color(204, 204, 204));
        userUniversitySem8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        userUniversitySem8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUniversitySem8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        saveEduUniversityInfo.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        saveEduUniversityInfo.setText("SAVE AND CONTINUE");
        saveEduUniversityInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        saveEduUniversityInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEduUniversityInfoActionPerformed(evt);
            }
        });

        EduHscSscToggle.setBackground(new java.awt.Color(51, 51, 51));
        EduHscSscToggle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        EduHscSscToggle.setForeground(new java.awt.Color(204, 204, 204));
        EduHscSscToggle.setText("EDUCATIONAL DETAILS SSC / HSC");
        EduHscSscToggle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        EduHscSscToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EduHscSscToggleActionPerformed(evt);
            }
        });

        userId.setEditable(false);
        userId.setBackground(new java.awt.Color(51, 51, 51));
        userId.setBorder(null);
        userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(userId, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                        .addGap(129, 129, 129))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userUniversityBatchYear, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(userUniversityCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(userUniversityBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(425, 425, 425)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(userUniversitySem5, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                .addComponent(userUniversitySem6))
                                            .addComponent(userUniversitySem7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(userUniversitySem8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(userUniversityDegreeName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EduHscSscToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(proectToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(experienceToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userUniversitySem4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(userUniversitySem3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(userUniversitySem2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(userUniversitySem1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveEduUniversityInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(generalToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1064, 1064, 1064)))))
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmationToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proectToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(experienceToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmationToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EduHscSscToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generalToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userUniversityDegreeName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userUniversitySem5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userUniversitySem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userUniversityBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userUniversitySem6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userUniversitySem2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userUniversityBatchYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userUniversitySem7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userUniversitySem3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userUniversityCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userUniversitySem4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userUniversitySem8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(saveEduUniversityInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmationToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationToggleActionPerformed
Confirmation CO = new Confirmation();
    String _id = userId.getText();
    CO.get_edu_confirm_detail(_id);
CO.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_confirmationToggleActionPerformed

    private void generalToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalToggleActionPerformed
        GeneralDetails GD = new GeneralDetails();
        String _id = userId.getText();
        GD.get_general_detail(_id);
GD.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_generalToggleActionPerformed

    private void EduHscSscToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EduHscSscToggleActionPerformed
        EducationDetailsHS EDHS = new EducationDetailsHS();
        String _id = userId.getText();
        EDHS.get_edu_school_detail(_id);
        EDHS.show();
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_EduHscSscToggleActionPerformed

    private void saveEduUniversityInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEduUniversityInfoActionPerformed
ProjectDetails PJ = new ProjectDetails();

        String _id = userId.getText();
        PJ.get_edu_intern_detail(_id);
        String _userUniversityDegreeName = userUniversityDegreeName.getText();
	String _userUniversityBranch = userUniversityBranch.getText();
        String _userUniversityBatchYear = userUniversityBatchYear.getText();
        String _userUniversityCollegeName = userUniversityCollegeName.getText();
        String _userUniversitySem1 = userUniversitySem1.getText();
        String _userUniversitySem2 = userUniversitySem2.getText();
        String _userUniversitySem3 = userUniversitySem3.getText();
        String _userUniversitySem4 = userUniversitySem4.getText();
        String _userUniversitySem5 = userUniversitySem5.getText();
        String _userUniversitySem6 = userUniversitySem6.getText();
        String _userUniversitySem7 = userUniversitySem7.getText();
        String _userUniversitySem8 = userUniversitySem8.getText();
        Transaction obj = new Transaction();
        obj.set_edu_university_info(_id, _userUniversityDegreeName, _userUniversityBranch, _userUniversityBatchYear, _userUniversityCollegeName, _userUniversitySem1, _userUniversitySem2, _userUniversitySem3, _userUniversitySem4, _userUniversitySem5, _userUniversitySem6, _userUniversitySem7, _userUniversitySem8);


PJ.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_saveEduUniversityInfoActionPerformed

    private void experienceToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experienceToggleActionPerformed
ExperienceDetails EXP = new ExperienceDetails();
   String _id = userId.getText();
   EXP.get_edu_experience_detail(_id);
EXP.show();
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_experienceToggleActionPerformed

    private void proectToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proectToggleActionPerformed
ProjectDetails PJ = new ProjectDetails();
String _id = userId.getText();
PJ.get_edu_intern_detail(_id);
PJ.show();
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_proectToggleActionPerformed

    private void userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdActionPerformed

    private void userUniversitySem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userUniversitySem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userUniversitySem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EducationalDetailsUni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EducationalDetailsUni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EducationalDetailsUni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EducationalDetailsUni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EducationalDetailsUni().setVisible(true);
            }
        });
    }
    
    void get_edu_university_detail(String id)
    {
       
       try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/resume","root","Dalbir@P3517");
            
            String check_query = "Select * from eduinfo Where userid='" + id + "'";
            java.sql.PreparedStatement ps = con.prepareStatement(check_query);
            java.sql.ResultSet resultSet = ps.executeQuery(check_query);
              while (resultSet.next()) {
                  String  _userid = resultSet.getString("userid");
                  String  _userUniversityDegreeName = resultSet.getString("userUniversityDegreeName");
                  String  _userUniversityBranch = resultSet.getString("userUniversityBranch");
                  String  _userUniversityBatchYear = resultSet.getString("userUniversityBatchYear");
                  String  _userUniversityCollegeName = resultSet.getString("userUniversityCollegeName");
                  String  _userUniversitySem1 = resultSet.getString("userUniversitySem1");
                  String  _userUniversitySem2 = resultSet.getString("userUniversitySem2");
                  String  _userUniversitySem3 = resultSet.getString("userUniversitySem3");
                  String  _userUniversitySem4 = resultSet.getString("userUniversitySem4");
                  String  _userUniversitySem5 = resultSet.getString("userUniversitySem5");
                  String  _userUniversitySem6 = resultSet.getString("userUniversitySem6");
                  String  _userUniversitySem7 = resultSet.getString("userUniversitySem7");
                  String  _userUniversitySem8 = resultSet.getString("userUniversitySem8");

                    userUniversityDegreeName.setText(_userUniversityDegreeName);
                    userUniversityBranch.setText(_userUniversityBranch);
                    userUniversityBatchYear.setText(_userUniversityBatchYear);
                    userUniversityCollegeName.setText(_userUniversityCollegeName);
                    userUniversitySem1.setText(_userUniversitySem1);
                    userUniversitySem2.setText(_userUniversitySem2);
                    userUniversitySem3.setText(_userUniversitySem3);
                    userUniversitySem4.setText(_userUniversitySem4);
                    userUniversitySem5.setText(_userUniversitySem5);
                    userUniversitySem6.setText(_userUniversitySem6);
                    userUniversitySem7.setText(_userUniversitySem7);
                    userUniversitySem8.setText(_userUniversitySem8);
                    userId.setText(_userid);

             }
            
           con.close();
          
	}catch(Exception e){ System.out.println(e);} 
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EduHscSscToggle;
    private javax.swing.JButton confirmationToggle;
    private javax.swing.JButton experienceToggle;
    private javax.swing.JButton generalToggle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton proectToggle;
    private javax.swing.JButton saveEduUniversityInfo;
    private javax.swing.JTextField userId;
    private javax.swing.JTextField userUniversityBatchYear;
    private javax.swing.JTextField userUniversityBranch;
    private javax.swing.JTextField userUniversityCollegeName;
    private javax.swing.JTextField userUniversityDegreeName;
    private javax.swing.JTextField userUniversitySem1;
    private javax.swing.JTextField userUniversitySem2;
    private javax.swing.JTextField userUniversitySem3;
    private javax.swing.JTextField userUniversitySem4;
    private javax.swing.JTextField userUniversitySem5;
    private javax.swing.JTextField userUniversitySem6;
    private javax.swing.JTextField userUniversitySem7;
    private javax.swing.JTextField userUniversitySem8;
    // End of variables declaration//GEN-END:variables
}
