
import java.sql.Connection;
import java.sql.DriverManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author mayan
 */
public class ExperienceDetails extends javax.swing.JFrame {

    /**
     * Creates new form experience
     */
    public ExperienceDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userExperienceCertificate = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        generalToogle = new javax.swing.JButton();
        universityToogle = new javax.swing.JButton();
        eduSscHscToggle = new javax.swing.JButton();
        projectToggle = new javax.swing.JButton();
        confirmationToogle = new javax.swing.JButton();
        SaveandContinue = new javax.swing.JButton();
        userId = new javax.swing.JTextField();
        certificateURL = new javax.swing.JLabel();
        userCertificateUrl = new javax.swing.JTextField();
        certificateURL2 = new javax.swing.JLabel();
        userCertificateBatch = new javax.swing.JTextField();
        userExperienceLanguagesKnown = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXPERIENCE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 5));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("CERTIFICATION");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        userExperienceCertificate.setColumns(20);
        userExperienceCertificate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userExperienceCertificate.setRows(5);
        jScrollPane1.setViewportView(userExperienceCertificate);

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LANGUAGES KNOWN");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        generalToogle.setBackground(new java.awt.Color(51, 51, 51));
        generalToogle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        generalToogle.setForeground(new java.awt.Color(204, 204, 204));
        generalToogle.setText("GENERAL");
        generalToogle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        generalToogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalToogleActionPerformed(evt);
            }
        });

        universityToogle.setBackground(new java.awt.Color(51, 51, 51));
        universityToogle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        universityToogle.setForeground(new java.awt.Color(204, 204, 204));
        universityToogle.setText("EDUCATIONAL DETAILS UNIVERSITY");
        universityToogle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        universityToogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityToogleActionPerformed(evt);
            }
        });

        eduSscHscToggle.setBackground(new java.awt.Color(51, 51, 51));
        eduSscHscToggle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        eduSscHscToggle.setForeground(new java.awt.Color(204, 204, 204));
        eduSscHscToggle.setText("EDUCATIONAL DETAILS SSC / HSC");
        eduSscHscToggle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        eduSscHscToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduSscHscToggleActionPerformed(evt);
            }
        });

        projectToggle.setBackground(new java.awt.Color(51, 51, 51));
        projectToggle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        projectToggle.setForeground(new java.awt.Color(204, 204, 204));
        projectToggle.setText("PROJECTS / INTERNSHIPS");
        projectToggle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        projectToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectToggleActionPerformed(evt);
            }
        });

        confirmationToogle.setBackground(new java.awt.Color(51, 51, 51));
        confirmationToogle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        confirmationToogle.setForeground(new java.awt.Color(204, 204, 204));
        confirmationToogle.setText("CONFIRMATION");
        confirmationToogle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        confirmationToogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationToogleActionPerformed(evt);
            }
        });

        SaveandContinue.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        SaveandContinue.setText("SAVE AND CONTINUE");
        SaveandContinue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        SaveandContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveandContinueActionPerformed(evt);
            }
        });

        userId.setEditable(false);
        userId.setBackground(new java.awt.Color(51, 51, 51));
        userId.setBorder(null);
        userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdActionPerformed(evt);
            }
        });

        certificateURL.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        certificateURL.setForeground(new java.awt.Color(204, 204, 204));
        certificateURL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certificateURL.setText("Certificate URL");
        certificateURL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        userCertificateUrl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        certificateURL2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        certificateURL2.setForeground(new java.awt.Color(204, 204, 204));
        certificateURL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certificateURL2.setText("Certificate Batch");
        certificateURL2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        userCertificateBatch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        userExperienceLanguagesKnown.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userExperienceLanguagesKnown.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userExperienceLanguagesKnown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userExperienceLanguagesKnownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(generalToogle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(eduSscHscToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(universityToogle, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(projectToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(confirmationToogle, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveandContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(certificateURL, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certificateURL2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userCertificateBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(userExperienceLanguagesKnown, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userCertificateUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generalToogle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduSscHscToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmationToogle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(universityToogle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userExperienceLanguagesKnown, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(certificateURL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userCertificateUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userCertificateBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(certificateURL2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(SaveandContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalToogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalToogleActionPerformed
GeneralDetails GD = new GeneralDetails();
        String _id = userId.getText();
        GD.get_general_detail(_id);
GD.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_generalToogleActionPerformed

    private void universityToogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityToogleActionPerformed
EducationalDetailsUni EDU = new EducationalDetailsUni();
     String _id = userId.getText();
     EDU.get_edu_university_detail(_id);
EDU.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_universityToogleActionPerformed

    private void eduSscHscToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduSscHscToggleActionPerformed
EducationDetailsHS EDHS = new EducationDetailsHS();
String _id = userId.getText();
EDHS.get_edu_school_detail(_id);
EDHS.show();
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_eduSscHscToggleActionPerformed

    private void confirmationToogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationToogleActionPerformed
Confirmation CO = new Confirmation();
    String _id = userId.getText();
    CO.get_edu_confirm_detail(_id);
CO.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_confirmationToogleActionPerformed

    private void SaveandContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveandContinueActionPerformed
    Confirmation CO = new Confirmation();
    
    
    String _id = userId.getText();
    CO.get_edu_confirm_detail(_id);
        
        
        String _userExperienceLanguagesKnown = userExperienceLanguagesKnown.getText();
	String _userExperienceCertificate = userExperienceCertificate.getText();
        String _userCertificateUrl = userCertificateUrl.getText();
        String _userCertificateBatch = userCertificateBatch.getText();


        
        Transaction obj = new Transaction();
        obj.set_edu_experience_info(_id, _userExperienceLanguagesKnown, _userExperienceCertificate,_userCertificateUrl,_userCertificateBatch);
    
CO.show();
dispose(); 

        // TODO add your handling code here:
    }//GEN-LAST:event_SaveandContinueActionPerformed

    private void projectToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectToggleActionPerformed
ProjectDetails PJ = new ProjectDetails();
String _id = userId.getText();
PJ.get_edu_intern_detail(_id);
PJ.show();
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_projectToggleActionPerformed

    private void userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdActionPerformed

    private void userExperienceLanguagesKnownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userExperienceLanguagesKnownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userExperienceLanguagesKnownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExperienceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExperienceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExperienceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExperienceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExperienceDetails().setVisible(true);
            }
        });
    }
    
    void get_edu_experience_detail(String id)
    {
       
       try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/resume","root","Dalbir@P3517");
            
            String check_query = "Select * from eduinfo Where userid='" + id + "'";
            java.sql.PreparedStatement ps = con.prepareStatement(check_query);
            java.sql.ResultSet resultSet = ps.executeQuery(check_query);
              while (resultSet.next()) {
                  String  _userid = resultSet.getString("userid");
                  String  _userExperienceLanguagesKnown = resultSet.getString("userExperienceLanguagesKnown");
                  String  _userExperienceCertificate = resultSet.getString("userExperienceCertificate");
                  String  _userCertificateUrl = resultSet.getString("userCertificateUrl");
                  String  _userCertificateBatch = resultSet.getString("userCertificateBatch");

                    userExperienceLanguagesKnown.setText(_userExperienceLanguagesKnown);
                    userExperienceCertificate.setText(_userExperienceCertificate);
                    userCertificateUrl.setText(_userCertificateUrl);
                    userCertificateBatch.setText(_userCertificateBatch);

                    userId.setText(_userid);

             }
            
           con.close();
          
	}catch(Exception e){ System.out.println(e);} 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveandContinue;
    private javax.swing.JLabel certificateURL;
    private javax.swing.JLabel certificateURL2;
    private javax.swing.JButton confirmationToogle;
    private javax.swing.JButton eduSscHscToggle;
    private javax.swing.JButton generalToogle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton projectToggle;
    private javax.swing.JButton universityToogle;
    private javax.swing.JTextField userCertificateBatch;
    private javax.swing.JTextField userCertificateUrl;
    private javax.swing.JTextArea userExperienceCertificate;
    private javax.swing.JTextField userExperienceLanguagesKnown;
    private javax.swing.JTextField userId;
    // End of variables declaration//GEN-END:variables
}
